In [1]:
import pandas as pd

In [2]:
cadUnico_2012 = pd.read_csv('../BasesCompletas/base_amostra_familia_201212_20190131.csv', sep=';', low_memory=False)
cadUnico_2013 = pd.read_csv('../BasesCompletas/base_amostra_familia_201312_20190131.csv', sep=';', low_memory=False)
cadUnico_2014 = pd.read_csv('../BasesCompletas/base_amostra_familia_201412_20190131.csv', sep=';', low_memory=False)
cadUnico_2015 = pd.read_csv('../BasesCompletas/base_amostra_familia_201512_20190131.csv', sep=';', low_memory=False)
cadUnico_2016 = pd.read_csv('../BasesCompletas/base_amostra_familia_201612_20190131.csv', sep=';', low_memory=False)
cadUnico_2017 = pd.read_csv('../BasesCompletas/base_amostra_familia_201712_20190131.csv', sep=';', low_memory=False)
cadUnico_2018 = pd.read_csv('../BasesCompletas/base_amostra_familia_201812.csv', sep=';', low_memory=False)

### Base BA/2012

In [3]:
cadunico_ba_2012 = cadUnico_2012[
    cadUnico_2012['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2012.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
817,2924009,2,3,746032,2001-11-19,2012-12-05,3,2.0,1.0,7.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"4,61314991205122",1
818,2924009,2,3,3068318,2001-11-19,2011-06-28,0,2.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"4,61314991205122",1
819,2924009,2,3,746033,2001-11-19,2011-05-03,136,2.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,4,"6,96662210898482",0
820,2924009,2,3,746049,2001-11-19,2012-02-17,50,1.0,1.0,4.0,...,2.0,2.0,USF BOA ESPERANCA,2549956.0,NaN,NaN,NaN,4,"4,61314991205122",1
821,2924009,2,3,746050,2001-11-19,2012-04-25,19,2.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3,"4,61314991205122",1

In [ ]:
cadunico_ba_2012.to_csv('BasesAno/cadunico_ba_2012.csv', index=False, sep=';')

### Base BA/2013

In [5]:
cadunico_ba_2013 = cadUnico_2013[
    cadUnico_2013['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2013.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
840,2924009,2,3,843539,2001-11-19,2011-05-03,136,2.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,4,"5,41540610151184",0
841,2924009,2,3,843557,2001-11-19,2013-09-06,400,2.0,1.0,5.0,...,2.0,2.0,USF MALHADA GRANDE,2507889.0,NaN,NaN,NaN,3,"5,41540610151184",0
842,2924009,2,3,3373425,2001-11-19,2013-01-10,4,2.0,1.0,6.0,...,2.0,2.0,USF SAO JOSE,2533286.0,NaN,NaN,NaN,4,"5,41540610151184",1
843,2924009,2,3,3373428,2001-11-19,2012-11-23,4,2.0,1.0,7.0,...,2.0,2.0,CENTRO MEDICO DE ESPECIALIDADES,2533499.0,NaN,NaN,NaN,5,"5,41540610151184",1
844,2924009,2,3,3373491,2001-11-19,2013-06-10,25,1.0,1.0,4.0,...,2.0,2.0,USF SANTA QUITERIA,2549921.0,NaN,NaN,NaN,4,"5,41540610151184",1

In [6]:
cadunico_ba_2013.to_csv('BasesAno/cadunico_ba_2013.csv', index=False, sep=';')

### Base BA/2014

In [7]:
cadunico_ba_2014 = cadUnico_2014[
    cadUnico_2014['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2014.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
754,2924009,2,3,3828693,2001-11-19,2014-12-11,144,2.0,1.0,6.0,...,2.0,2.0,POSTO DE SAUDE ARRASTAPE,2507994.0,NaN,NaN,0.0,5,"5,33488972093053",1
755,2924009,2,3,3828662,2001-11-19,2013-05-08,5,1.0,1.0,5.0,...,2.0,2.0,USF BOA ESPERANCA,2549956.0,NaN,NaN,0.0,3,"5,33488972093053",1
756,2924009,2,3,3828679,2001-11-19,2012-11-30,3,2.0,1.0,4.0,...,2.0,2.0,CENTRO MEDICO DE ESPECIALIDADES,2533499.0,NaN,NaN,205.0,2,"5,33488972093053",0
757,2924009,2,3,1078914,2001-11-19,2014-10-08,79,1.0,1.0,5.0,...,2.0,2.0,USF RODOVIARIO,2533294.0,NaN,NaN,0.0,4,"5,33488972093053",0
758,2924009,2,3,1078906,2001-11-19,2014-12-09,13,2.0,1.0,5.0,...,2.0,2.0,USF MALHADA GRANDE,2507889.0,NaN,NaN,0.0,3,"5,33488972093053",0

In [8]:
cadunico_ba_2014.to_csv('BasesAno/cadunico_ba_2014.csv', index=False, sep=';')

### Base BA/2015

In [9]:
cadunico_ba_2015 = cadUnico_2015[
    cadUnico_2015['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2015.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
1,2919207,2,2,2,2015-07-29,2015-08-12,75,2015-08-12,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,18705639548332",1
2,2910727,2,3,3,2002-06-13,2014-11-24,100,2014-11-24,1.0,1.0,...,2.0,2.0,UNIDADE BASICA DE SAUDE MOISES REIS I,2556650.0,NaN,NaN,0.0,2,"5,18728131676087",1
9,2903201,2,3,10,2012-03-23,2013-10-17,370,2012-08-01,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,18723458507705",0
11,2902906,2,3,12,2002-05-16,2014-07-01,11,2014-05-06,1.0,1.0,...,2.0,2.0,USF DO BAIRRO PEDRO SANTINO,2402777.0,NaN,NaN,0.0,6,"5,18705639548332",0
35,2911709,2,3,36,2012-07-17,2015-02-12,0,2015-02-12,2.0,1.0,...,2.0,2.0,UBS EUJACIO VIEIRA PRATES,2412691.0,NaN,NaN,205.0,2,"5,18752010983528",1

In [10]:
cadunico_ba_2015.to_csv('BasesAno/cadunico_ba_2015.csv', index=False, sep=';')

### Base BA/2016

In [11]:
cadunico_ba_2016 = cadUnico_2016[
    cadUnico_2016['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2016.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
3182,2919207,2,2,3953,2016-04-13,2016-04-13,0,2016-04-13,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,"5,33750934118856",1
3183,2918407,2,2,3954,2010-06-18,2015-03-10,35,2015-03-10,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,33782729090605",1
3184,2918407,2,2,3955,2004-04-02,2015-04-09,93,2015-04-09,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3,"5,33782729090605",1
3185,2919207,2,2,3956,2004-09-10,2013-04-05,170,2013-04-05,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,3,"5,33750934118856",0
3186,2921005,2,2,3957,2002-06-22,2016-11-30,180,2016-11-29,1.0,1.0,...,2.0,2.0,POSTO DE SAUDE DA FAMILIA SAUIPE,2627388.0,NaN,NaN,0.0,6,"5,33771960191186",0

In [12]:
cadunico_ba_2016.to_csv('BasesAno/cadunico_ba_2016.csv', index=False, sep=';')

### Base BA/2017

In [13]:
cadunico_ba_2017 = cadUnico_2017[
    cadUnico_2017['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2017.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
14,2924009,2,3,15,2013-10-23,2017-07-22,6,2017-07-21,1.0,1.0,...,2.0,2.0,USF JURACI SOARES DE MACEDO MOXOTO,2533510.0,NaN,NaN,0.0,3,"5,16802173842477",1
41,2905602,2,3,42,2012-07-13,2017-11-02,788,2015-12-21,1.0,1.0,...,2.0,2.0,USF LUIZ PEREIRA DE CASTRO,2771217.0,NaN,NaN,0.0,1,"5,17002188783795",0
60,2903409,2,3,61,2002-11-15,2015-06-25,73,2015-06-25,1.0,1.0,...,2.0,2.0,USF II JOSE TAURINO DE OLIVEIRA,2413930.0,CRAS DE BELMONTE CASA DA FAMILIA,2.903401e+10,202.0,3,"5,1694007404388",1
61,2915601,2,3,62,2009-01-30,2017-05-05,28,2017-05-04,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,6,"5,16877104119068",1
74,2927408,2,1,75,2014-11-13,2014-11-13,6,2014-11-13,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,"5,1685234424128",0

In [14]:
cadunico_ba_2017.to_csv('BasesAno/cadunico_ba_2017.csv', index=False, sep=';')

### Base BA/2018

In [15]:
cadunico_ba_2018 = cadUnico_2018[
    cadUnico_2018['cd_ibge'].astype(str).str.startswith('29')
]

cadunico_ba_2018.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas,peso.fam
383,2918407,2,2,499.0,2017-01-04,2018-09-26,122.0,2018-09-26,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,3,550233945611477
384,2910057,2,2,500.0,2003-02-18,2018-09-30,80.0,2018-06-07,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,2,550279629086944
385,2905701,2,2,501.0,2006-06-03,2018-09-30,312.0,2017-11-22,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,0,3,550269263053272
386,2918407,2,2,502.0,2011-07-18,2018-09-30,197.0,2015-09-18,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,0,4,550233945611477
387,2905701,2,2,503.0,2012-01-31,2018-10-01,12.0,2016-08-31,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,4,550269263053272

In [16]:
cadunico_ba_2018.to_csv('BasesAno/cadunico_ba_2018.csv', index=False, sep=';')

### Mesclando os dados

In [18]:
# Mesclando os arquivos CSV em um único DataFrame
cadunico_combined = pd.concat([cadUnico_2012, cadUnico_2013, cadUnico_2014, 
                              cadUnico_2015, cadUnico_2016, cadUnico_2017, cadUnico_2018], 
                              ignore_index=True)

In [19]:
# Filtrando os dados apenas para os municípios do RN
cadunico_ba_combined = cadunico_combined[cadunico_combined['cd_ibge'].astype(str).str.startswith('29')]

# Salvando o arquivo filtrado
cadunico_ba_combined.to_csv('cadunico_ba_combined.csv', index=False, sep=';')