In [1]:
import pandas as pd

In [2]:
cadunico_2012 = pd.read_csv("../BasesCompletas/base_amostra_familia_201212_20190131.csv", sep = ";", low_memory=False)
cadunico_2013 = pd.read_csv("../BasesCompletas/base_amostra_familia_201312_20190131.csv", sep = ";", low_memory=False)
cadunico_2014 = pd.read_csv("../BasesCompletas/base_amostra_familia_201412_20190131.csv", sep = ";", low_memory=False)
cadunico_2015 = pd.read_csv("../BasesCompletas/base_amostra_familia_201512_20190131.csv", sep = ";", low_memory=False)
cadunico_2016 = pd.read_csv("../BasesCompletas/base_amostra_familia_201612_20190131.csv", sep = ";", low_memory=False)
cadunico_2017 = pd.read_csv("../BasesCompletas/base_amostra_familia_201712_20190131.csv", sep = ";", low_memory=False)
cadunico_2018 = pd.read_csv("../BasesCompletas/base_amostra_familia_201812.csv", sep = ";", low_memory=False)

## Base PI/2012

In [3]:
cadunico_pi_2012 = cadunico_2012[
    cadunico_2012['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2012.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
816,2202729,1,3,4533964,2001-11-19,2011-10-25,109,2.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"4,61361189780315",1
4091,2206506,1,3,4448870,2001-11-29,2012-12-13,323,2.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"4,61361189780315",1
4092,2206506,1,3,2126512,2001-11-29,2011-10-28,3,2.0,1.0,5.0,...,2.0,2.0,UNIDADE MISTA DE SAUDE MONSENHOR HIPOLITO,2323591.0,NaN,NaN,NaN,6,"4,61361189780315",1
4093,2206506,1,3,4448891,2001-11-29,2012-04-03,20,2.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"4,61361189780315",1
4094,2206506,1,3,2126528,2001-11-29,2012-09-24,0,2.0,1.0,2.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1,"4,61361189780315",1

In [4]:
cadunico_pi_2012.to_csv('BasesAno/cadunico_pi_2012.csv', index=False, sep=';')

## Base PI/2013

In [5]:
cadunico_pi_2013 = cadunico_2013[
    cadunico_2013['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2013.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
3984,2206506,1,3,4869816,2001-11-29,2012-12-13,323,2.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"5,41496051710077",1
3985,2206506,1,3,2337860,2001-11-29,2012-11-19,20,2.0,1.0,4.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,4,"5,41496051710077",1
3986,2206506,1,3,2337861,2001-11-29,2013-10-29,6,2.0,1.0,6.0,...,2.0,2.0,UMS EMILIA DE SA BEZERRA,2323591.0,NaN,NaN,NaN,4,"5,41496051710077",1
3987,2206506,1,3,2337888,2001-11-29,2012-10-30,12,1.0,1.0,4.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3,"5,41496051710077",1
3988,2204303,1,3,4838764,2001-11-30,2013-06-17,207,1.0,NaN,NaN,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"5,41496051710077",0

In [6]:
cadunico_pi_2013.to_csv('BasesAno/cadunico_pi_2013.csv', index=False, sep=';')

## Base PI/2014

In [7]:
cadunico_pi_2014 = cadunico_2014[
    cadunico_2014['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2014.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
3759,2206506,1,3,865319,2001-11-29,2014-05-21,27,1.0,1.0,5.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,3,"5,3353350560452",1
3760,2206506,1,3,3615449,2001-11-29,2012-01-27,0,2.0,1.0,4.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1,"5,3353350560452",0
3761,2204303,1,3,2750748,2001-11-30,2012-07-18,7,1.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"5,3353350560452",0
3762,2204303,1,3,1452,2001-11-30,2012-08-09,50,1.0,1.0,4.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3,"5,3353350560452",0
3763,2206506,1,3,3615441,2001-11-30,2014-11-26,17,2.0,1.0,6.0,...,2.0,2.0,UMS EMILIA DE SA BEZERRA,2323591.0,NaN,NaN,0.0,1,"5,3353350560452",1

In [8]:
cadunico_pi_2014.to_csv('BasesAno/cadunico_pi_2014.csv', index=False, sep=';')

## Base PI/2015

In [9]:
cadunico_pi_2015 = cadunico_2015[
    cadunico_2015['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2015.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
81,2211001,2,1,82,2012-07-30,2012-07-30,175,2012-07-30,1.0,1.0,...,2.0,2.0,NaN,NaN,CRAS SUL IV,2.211002e+10,NaN,2,"5,18696863384393",0
95,2204659,1,3,96,2003-03-13,2015-02-06,181,2015-02-06,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,4,"5,18704201444328",0
107,2201929,1,3,108,2006-09-27,2015-06-11,2,2015-06-11,1.0,2.0,...,2.0,2.0,PS DE BONFIM,2365715.0,CENTRO DE REFERENCIA DE ASSISTENCIA SOCIAL,2.201921e+10,0.0,3,"5,18704201444328",1
119,2204659,1,3,120,2002-12-17,2015-11-04,20,2015-11-04,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,202.0,3,"5,18704201444328",1
133,2211001,2,1,134,2008-05-07,2014-09-23,44,2014-09-23,1.0,1.0,...,2.0,2.0,CENTRO DE SAUDE DR MARIANO MENDES MONTE ALEGRE,2443821.0,CRAS NORTE I,2.211000e+10,0.0,5,"5,18696863384393",1

In [ ]:
cadunico_pi_2015.to_csv('BasesAno/cadunico_pi_2015.csv', index=False, sep=';')

## Base PI/2016

In [11]:
cadunico_pi_2016 = cadunico_2016[
    cadunico_2016['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2016.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
7537,2201606,1,2,9334,2007-10-10,2015-06-01,0,2015-06-01,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,5,"5,33771960191186",1
7538,2201606,1,2,9335,2003-03-13,2016-11-17,0,2016-08-29,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,3,"5,33771960191186",1
7539,2203305,1,2,9338,2016-08-10,2016-08-10,20,2016-08-10,1.0,2.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,"5,33771960191186",1
7540,2205557,1,2,9339,2002-08-21,2016-10-15,30,2016-10-14,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,33771960191186",1
7541,2202737,1,2,9340,2008-05-30,2015-04-22,315,2015-04-22,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"5,33771960191186",0

In [12]:
cadunico_pi_2016.to_csv('BasesAno/cadunico_pi_2016.csv', index=False, sep=';')

## Base PI/2017

In [13]:
cadunico_pi_2017 = cadunico_2017[
    cadunico_2017['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2017.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
45,2209708,1,3,46,2006-06-17,2017-03-30,3,2017-03-29,2.0,1.0,...,2.0,2.0,UMS DE SAO FRANCISCO DO PIAUI,2324210.0,CENTRO DE REFERENCIA DA ASSISTENCIA SOCIAL,2.209700e+10,0.0,4,"5,16850788329594",1
121,2201507,2,3,123,2011-07-08,2015-09-28,1,2015-09-28,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1,"5,1700173172582",1
135,2211001,2,1,137,2016-01-13,2017-09-20,1,2017-09-19,1.0,1.0,...,2.0,2.0,NaN,NaN,CRAS SUL II IRMA DULCE,2.211000e+10,0.0,3,"5,16845618767973",1
155,2207702,2,3,157,2017-05-15,2017-05-17,425,2017-05-15,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,16900750857698",0
161,2202208,2,3,163,2013-07-22,2017-10-10,937,2017-10-09,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,"5,16753653798268",0

In [14]:
cadunico_pi_2017.to_csv('BasesAno/cadunico_pi_2017.csv', index=False, sep=';')

## Base PI/2018

In [15]:
cadunico_pi_2018 = cadunico_2018[
    cadunico_2018['cd_ibge'].astype(str).str.startswith('22')
]

cadunico_pi_2018.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas,peso.fam
13325,2211100,2,2,16733.0,2005-09-09,2016-05-18,0.0,2016-05-18,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,2,550141358056398
13326,2201606,1,2,16734.0,2006-05-26,2018-09-30,20.0,2017-09-21,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,3,550270507728272
13327,2205508,2,2,16735.0,2016-12-15,2018-10-01,311.0,2017-01-31,1.0,2.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,3,550245146328323
13328,2205508,2,2,16736.0,2007-02-15,2018-11-29,0.0,2018-11-29,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,2,550245146328323
13329,2200400,2,2,16737.0,2003-03-13,2018-09-30,115.0,2017-11-08,2.0,1.0,...,2.0,2.0,HOSP DE ALTOS INST DE SAUDE JOSE GIL BARBOSA,2324075.0,CENTRO DE REFERENCIA DA ASSISTENCIA SOCIAL CAS...,2.200400e+10,0.0,1,3,550095557697059

In [16]:
cadunico_pi_2018.to_csv('BasesAno/cadunico_pi_2018.csv', index=False, sep=';')

## Mesclando os dados

In [17]:
# Adiciona a coluna ano em cada base
for ano, df in [
    (2012, cadunico_2012),
    (2013, cadunico_2013),
    (2014, cadunico_2014),
    (2015, cadunico_2015),
    (2016, cadunico_2016),
    (2017, cadunico_2017),
    (2018, cadunico_2018),
]:
    df["ano"] = ano

In [18]:
# Mesclando os arquivos CSV em um único DataFrame
cadunico_combined = pd.concat([cadunico_2012, cadunico_2013, cadunico_2014,
                              cadunico_2015, cadunico_2016, cadunico_2017, cadunico_2018],
                              ignore_index=True)

In [19]:
# Filtrando os dados apenas para os municípios do RN
cadunico_pi_combined = cadunico_combined[cadunico_combined['cd_ibge'].astype(str).str.startswith('22')]

# Salvando o arquivo filtrado
cadunico_pi_combined.to_csv('cadunico_pi_combined.csv', index=False, sep=';')