In [1]:
import pandas as pd

In [2]:
cadunico_2012 = pd.read_csv("../BasesCompletas/base_amostra_familia_201212_20190131.csv", sep = ";", low_memory=False)
cadunico_2013 = pd.read_csv("../BasesCompletas/base_amostra_familia_201312_20190131.csv", sep = ";", low_memory=False)
cadunico_2014 = pd.read_csv("../BasesCompletas/base_amostra_familia_201412_20190131.csv", sep = ";", low_memory=False)
cadunico_2015 = pd.read_csv("../BasesCompletas/base_amostra_familia_201512_20190131.csv", sep = ";", low_memory=False)
cadunico_2016 = pd.read_csv("../BasesCompletas/base_amostra_familia_201612_20190131.csv", sep = ";", low_memory=False)
cadunico_2017 = pd.read_csv("../BasesCompletas/base_amostra_familia_201712_20190131.csv", sep = ";", low_memory=False)
cadunico_2018 = pd.read_csv("../BasesCompletas/base_amostra_familia_201812.csv", sep = ";", low_memory=False)

## Base CE/2012

In [3]:
cadunico_ce_2012 = cadunico_2012[
    cadunico_2012['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2012.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
35,2300606,1,3,2171095,2001-11-19,2011-10-26,0,2.0,1.0,6.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,NaN,4,"4,61366145115634",1
36,2300606,1,3,2171101,2001-11-19,2011-08-29,0,2.0,1.0,7.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,NaN,3,"4,61366145115634",1
37,2300606,1,3,4493623,2001-11-19,2011-12-14,0,2.0,1.0,4.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,NaN,5,"4,61366145115634",1
38,2300606,1,3,4493648,2001-11-19,2012-05-31,0,2.0,1.0,4.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,SUSTENTABILIDADE E CIDADANIA,2.300600e+10,NaN,6,"4,61366145115634",1
39,2300606,1,3,4493658,2001-11-19,2011-11-18,68,2.0,1.0,7.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,NaN,4,"4,61366145115634",1

In [5]:
cadunico_ce_2012.to_csv('BasesAno/cadunico_ce_2012.csv', index=False, sep=';')

## Base CE/2013

In [6]:
cadunico_ce_2013 = cadunico_2013[
    cadunico_2013['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2013.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
34,2300606,1,3,4915774,2001-11-19,2011-12-16,109,2.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"5,41492726692667",1
35,2300606,1,3,4915775,2001-11-19,2012-11-09,380,2.0,NaN,NaN,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,1,"5,41492726692667",0
36,2300606,1,3,2383793,2001-11-19,2013-08-28,0,2.0,1.0,9.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,CRAS SAO ROMAO,2.300602e+10,NaN,5,"5,41492726692667",1
37,2300606,1,3,4915867,2001-11-19,2011-12-09,18,2.0,1.0,6.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,CRAS SAO ROMAO,2.300602e+10,NaN,5,"5,41492726692667",0
38,2300606,1,3,4915868,2001-11-19,2011-12-19,0,2.0,1.0,6.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,5,"5,41492726692667",1

In [7]:
cadunico_ce_2013.to_csv('BasesAno/cadunico_ce_2013.csv', index=False, sep=';')

## Base CE/2014

In [8]:
cadunico_ce_2014 = cadunico_2014[
    cadunico_2014['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2014.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
29,2300606,1,3,3901417,2001-11-19,2013-12-09,226,2.0,1.0,5.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,0.0,3,"5,33537509688686",0
30,2300606,1,3,3901436,2001-11-19,2013-11-22,226,1.0,1.0,4.0,...,2.0,2.0,CENTRO DE SAUDE DE ALTANEIRA,2527308.0,NaN,NaN,205.0,3,"5,33537509688686",0
31,2300606,1,3,1151510,2001-11-19,2014-01-23,0,2.0,1.0,4.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,CRAS SUSTENTABILIDADE E CIDADANIA,2.300600e+10,205.0,5,"5,33537509688686",1
32,2300606,1,3,1151516,2001-11-19,2013-07-03,452,2.0,1.0,4.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,CRAS SAO ROMAO,2.300602e+10,0.0,3,"5,33537509688686",0
33,2300606,1,3,3901456,2001-11-19,2014-02-03,0,2.0,1.0,5.0,...,2.0,2.0,POSTO DE SAUDE DE SAO ROMAO,2527294.0,NaN,NaN,0.0,4,"5,33537509688686",1

In [9]:
cadunico_ce_2014.to_csv('BasesAno/cadunico_ce_2014.csv', index=False, sep=';')

## Base CE/2015

In [10]:
cadunico_ce_2015 = cadunico_2015[
    cadunico_2015['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2015.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
6,2307635,1,3,7,2002-02-22,2015-10-21,28,2015-10-21,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,4,"5,18703748044965",1
39,2305902,2,3,40,2002-07-01,2014-09-08,13,2014-06-20,2.0,1.0,...,2.0,2.0,POSTO DE SAUDE DE LIVRAMENTO,2480204.0,NaN,NaN,205.0,9,"5,18649835976903",1
57,2304103,2,3,58,2015-05-25,2015-06-02,394,2015-06-02,1.0,1.0,...,2.0,2.0,PSF DO BAIRRO CENTRO,2480948.0,NaN,NaN,0.0,2,"5,18776461078077",0
68,2305407,2,3,69,2013-04-05,2015-06-12,87,2015-06-12,2.0,1.0,...,2.0,2.0,ESF CRUZEIRINHO,2499207.0,CRAS II IRINEIDE PENAFORTE,2.305400e+10,0.0,3,"5,18677173849499",1
86,2302404,2,3,87,2002-03-25,2015-02-19,0,2015-02-19,1.0,1.0,...,2.0,2.0,CENTRO DE SAUDE DE BOA VIAGEM,2479125.0,CRAS FRANCISCO SALES DO NASCIMENTO CRAS II,2.302400e+10,0.0,6,"5,1863259352934",1

In [11]:
cadunico_ce_2015.to_csv('BasesAno/cadunico_ce_2015.csv', index=False, sep=';')

## Base CE/2016

In [12]:
cadunico_ce_2016 = cadunico_2016[
    cadunico_2016['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2016.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
24417,2301901,2,2,28792,2016-07-27,2016-07-27,61,2016-07-27,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2,"5,33813818709394",1
24418,2307304,2,2,28793,2002-05-31,2016-07-25,35,2016-07-25,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,7,"5,33781471319206",1
24419,2309706,2,2,28794,2004-01-29,2015-07-23,262,2015-07-14,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,3,"5,33733719273404",0
24420,2310209,2,2,28796,2007-03-28,2015-03-18,33,2015-03-18,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3,"5,33642005675267",1
24421,2307700,2,2,28797,2011-07-22,2015-04-15,50,2015-04-15,2.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,2,"5,33812552843916",1

In [13]:
cadunico_ce_2016.to_csv('BasesAno/cadunico_ce_2016.csv', index=False, sep=';')

## Base CE/2017

In [14]:
cadunico_ce_2017 = cadunico_2017[
    cadunico_2017['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2017.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,qtde_pessoas,peso.fam,marc_pbf
36,2311900,1,3,37,2002-10-25,2017-06-20,0,2017-04-18,1.0,1.0,...,2.0,2.0,CENTRO DE SAUDE DE SABOEIRO,2371901.0,NaN,NaN,0.0,3,"5,16846967598306",1
69,2304400,2,1,70,2016-02-01,2016-02-01,41,2016-02-01,1.0,1.0,...,2.0,2.0,C S F PROF JOSE SOBREIRA DE AMORIM,2528967.0,NaN,NaN,0.0,1,"5,16853436704816",1
73,2304707,2,3,74,2010-10-08,2016-04-15,42,2016-04-15,2.0,1.0,...,2.0,2.0,UNID BASICA DE SAUDE INACIO FELIX DOS SANTOS,2610965.0,CRAS JOSE FROTA VIANA,2.304700e+10,0.0,4,"5,16850788329594",1
76,2304103,2,3,77,2014-07-02,2017-11-06,50,2017-11-06,2.0,1.0,...,2.0,2.0,PSF DO DISTRITO DE MONTE NEBO,2480999.0,NaN,NaN,205.0,3,"5,16816222135332",1
160,2304400,2,1,162,2016-12-12,2017-01-12,4,2017-01-11,1.0,1.0,...,2.0,2.0,C S F TURBAY BARREIRA,2645114.0,CRAS VILA UNIAO,2.304400e+10,0.0,2,"5,16853436704816",1

In [15]:
cadunico_ce_2017.to_csv('BasesAno/cadunico_ce_2017.csv', index=False, sep=';')

## Base CE/2018

In [16]:
cadunico_ce_2018 = cadunico_2018[
    cadunico_2018['cd_ibge'].astype(str).str.startswith('23')
]

cadunico_ce_2018.head()

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas,peso.fam
4834,2307650,2,2,6114.0,2003-11-08,2018-09-30,50.0,2018-05-30,1.0,1.0,...,2.0,2.0,CENTRO DE SAUDE JOAO BATISTA DOS SANTOS,2372282.0,CRAS PAJUCARA,2.307652e+10,0.0,1,2,550257980003888
4835,2310852,2,2,6115.0,2003-03-13,2018-09-30,116.0,2018-01-08,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,205.0,0,6,550078895289254
4836,2303709,2,2,6116.0,2017-09-18,2018-10-01,468.0,2017-09-18,1.0,1.0,...,2.0,2.0,U B S TEREZINHA LIMA MOREIRA,3011704.0,CRAS EDSON DA MOTA CORREA,2.303700e+10,0.0,0,2,550254652031745
4837,2313500,2,2,6117.0,2013-06-17,2018-10-01,30.0,2017-06-28,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,1,550310484453119
4838,2307304,2,2,6118.0,2006-08-23,2018-11-20,100.0,2018-11-20,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,4,550245146328323

In [17]:
cadunico_ce_2018.to_csv('BasesAno/cadunico_ce_2018.csv', index=False, sep=';')

## Mesclando os dados

In [20]:
# Adiciona a coluna ano em cada base
for ano, df in [
    (2012, cadunico_2012),
    (2013, cadunico_2013),
    (2014, cadunico_2014),
    (2015, cadunico_2015),
    (2016, cadunico_2016),
    (2017, cadunico_2017),
    (2018, cadunico_2018),
]:
    df["ano"] = ano

In [21]:
# Mesclando os arquivos CSV em um único DataFrame
cadunico_combined = pd.concat([cadunico_2012, cadunico_2013, cadunico_2014,
                              cadunico_2015, cadunico_2016, cadunico_2017, cadunico_2018],
                              ignore_index=True)

In [22]:
# Filtrando os dados apenas para os municípios do RN
cadunico_ce_combined = cadunico_combined[cadunico_combined['cd_ibge'].astype(str).str.startswith('23')]

# Salvando o arquivo filtrado
cadunico_ce_combined.to_csv('cadunico_ce_combined.csv', index=False, sep=';')